# Generated by Django 2.2.3 on 2019-09-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='name')),
                ('slug', models.CharField(max_length=50)),
                ('description', models.TextField(default='This is one of the authors of this blog.', verbose_name='description')),
                ('description_en', models.TextField(default='This is one of the authors of this blog.', null=True, verbose_name='description')),
                ('joined_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('description_en', models.CharField(max_length=300, null=True, verbose_name='description')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('name_en', models.CharField(max_length=20, null=True, verbose_name='name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('description_en', models.CharField(max_length=300, null=True, verbose_name='description')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('description_en', models.CharField(max_length=300, null=True, verbose_name='description')),
                ('slug', models.SlugField()),
                ('content', models.TextField(help_text='HTML is the only available format currently for content.', verbose_name='content')),
                ('content_en', models.TextField(help_text='HTML is the only available format currently for content.', null=True, verbose_name='content')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='authors', to='Blog.Author')),
                ('categories', models.ManyToManyField(related_name='posts', to='Blog.Category')),
                ('tags', models.ManyToManyField(related_name='posts', to='Blog.Tag')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
